require 'mix-rails-core/railtie'
require 'mix-rails-core/engine'
require 'enumerize'
require 'fancybox-rails'
require 'rails-i18n'
require 'activevalidators'
require 'i18n_routing'
require 'simple-navigation'
require 'simple-navigation-bootstrap'
require 'breadcrumbs'
require 'will_paginate'
require 'coffee-script'
require 'carrierwave'
require 'mini_magick'
require 'haml_coffee_assets'
require 'mail_form'
require 'simple_form'
require 'rails-backbone'
require 'bootstrap-sass'
require 'jquery-qtip2-rails'
require 'authority'
require 'default_value_for'

module MixRailsCore
end
